### ISSUE TITLE
The JavaScriptCompiler API docs sample code is broken as of 4.6

### ISSUE THREAD

**Issue by romannurik** [handlebars-lang/handlebars.js#1912]
Just a note, that the [sample code for subclassing JavaScriptCompiler in the docs](https://github.com/handlebars-lang/handlebars.js/blob/master/docs/compiler-api.md#javascript-compiler) is broken as of ~4.6 with:

    TypeError: name.toLowerCase is not a function

(It works with handlebars 4.5 but fails with 4.6)

You can test this by swapping the handlebars.js version used in the [linked jsfiddle](https://jsfiddle.net/9D88g/162/) with the latest version (4.7.7).
